config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  resources :job_applications, only: [:create, :destroy]
  resources :muso_imgs
  resources :muso_embeds
  resources :musos
  resources :jobs
  resources :hosts, except: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/login', to: 'logins#muso_or_host_login'

  get '/login/musos', to: 'logins#musos'
  post '/login/musos', to: 'logins#muso_session'

  get '/login/hosts', to: 'logins#hosts'
  post '/login/hosts', to: 'logins#host_session'

  delete '/session', to: 'logins#delete_session'

  get "/search/musos", to: 'search#muso_results'
  get "/browse/musos", to: 'search#browse_all_musos'
  get '/signup', to: 'logins#muso_or_host_signup'
  
  post "/musos/:id/tags", to: 'musos#create_tags'
  delete "/musos/:id/tags", to: 'musos#destroy_tags'

  put '/job_applications/:id/reject', to: 'job_applications#reject'
  put 'jobs/:id/completed', to: 'jobs#mark_job_completed'

  put 'jobs/:id/select_successful_applicant', to: 'jobs#select_successful_applicant'

  get "/host/jobs/past", to: "hosts#old_host_jobs"
  get "/host/jobs", to: "hosts#host_jobs"

  get "/muso/jobs/past", to: "musos#old_muso_jobs"
  get "/muso/jobs", to: "musos#muso_jobs"
  get "/muso/jobs/applied", to: "musos#muso_applied_jobs"

  get '/jobs/:job_id/review', to: 'muso_reviews#review_job'
  post '/jobs/:job_id/review', to: 'muso_reviews#create'
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
    
    def muso_results
        @fltrs = params

        queries= []
        
        queries << [:search_by_name, @fltrs[:name_q]] unless @fltrs[:name_q].empty?

        queries << [:search_by_loc, @fltrs[:location_q]] unless @fltrs[:location_q].empty?

        queries << [:tagged_with, @fltrs[:key_words].split(" "), :any => true, :wild => true] unless @fltrs[:key_words].empty?
        min_price = @fltrs[:bprice_min].empty? ? 0 : @fltrs[:bprice_min].to_f
        max_price = @fltrs[:bprice_max].empty? ? 9999999 : @fltrs[:bprice_max].to_f

        queries << [:where, :base_price => min_price..max_price] 

        min_rating = @fltrs[:min_rating].empty? ? 0 : @fltrs[:min_rating].to_i
        
        @muso_results = queries.inject(Muso) { |obj, method_and_args| obj.send(*method_and_args) }.select { |result| result.average_rating >= min_rating }
    end

    def browse_all_musos
        @muso_results = Muso.all
        render :muso_results
    end
end

app/views/search/muso_results.html.erb
<%= link_to "Clear Filters", browse_musos_path %>
<form action="/search/musos" method="get" style="display:flex; flex-wrap:wrap;">
    name
    <input class="input-left" type="text" name="name_q" value="<%= @fltrs[:name_q] if !!@fltrs %>">
    location
    <input class="input-left" type="text" name="location_q" value="<%= @fltrs[:loc_q] if !!@fltrs %>">
    keywords (comma seperated):
    <input class="input-left" type="text" name="key_words" value="<%= @fltrs[:key_words] if !!@fltrs%>">
    Minimum rating:
    <input class="input-left" type="number" min="0" max="4" name="min_rating" value="<%= @fltrs[:min_rating] if !!@fltrs %>">
    base price:
    min
    <input class="input-left" type="number" min="0" name="bprice_min" value="<%= @fltrs[:bprice_min] if !!@fltrs %>">
    max
    <input class="input-left" type="number" min="0" name="bprice_max" value="<%= @fltrs[:bprice_max] if !!@fltrs %>">


    <button class="submit-btn">Search...</button>
</form>

<% @muso_results.each do |muso| %>
    <a href="/musos/<%= muso.id %>">
        <div class="tile" style="background-image: url(<%= muso.avatar.url(:view) %>);">
            <div class="text">
                <h2><%= muso.name %></h2>
                <p><%= muso.location %></p>
            </div>
        </div>
    </a>
<% end %>